#include "DXCaps.h"
#include <d3d11_1.h>

const int32_t DXCaps::CONSTANT_BUFFER_CONSTANT_SIZE = 16;
const int32_t DXCaps::CONSTANT_BUFFER_MAX_SIZE = DXCaps::CONSTANT_BUFFER_CONSTANT_SIZE * D3D11_REQ_CONSTANT_BUFFER_ELEMENT_COUNT;
const int32_t DXCaps::CONSTANT_BUFFER_ALIGNMENT = 256;